/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiappgradecalculator;

/**
 *
 * @author Amy
 */
public class GradeCalculator extends javax.swing.JFrame {

    /**
     * Creates new form GradeCalculator
     */
    public GradeCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Sub1 = new javax.swing.JTextField();
        Sub2 = new javax.swing.JTextField();
        Sub3 = new javax.swing.JTextField();
        Sub4 = new javax.swing.JTextField();
        Sub5 = new javax.swing.JTextField();
        Grade1 = new javax.swing.JTextField();
        Grade2 = new javax.swing.JTextField();
        Grade3 = new javax.swing.JTextField();
        Grade4 = new javax.swing.JTextField();
        Grade5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        totAvg1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Subject 1");

        jLabel2.setText("Subject 2");

        jLabel3.setText("Subject 3");

        jLabel4.setText("Subject 4");

        jLabel5.setText("Subject 5");

        Sub1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sub1ActionPerformed(evt);
            }
        });

        Sub2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sub2ActionPerformed(evt);
            }
        });

        Sub3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sub3ActionPerformed(evt);
            }
        });

        Sub4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sub4ActionPerformed(evt);
            }
        });

        Sub5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sub5ActionPerformed(evt);
            }
        });

        Grade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grade1ActionPerformed(evt);
            }
        });

        Grade2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grade2ActionPerformed(evt);
            }
        });

        Grade3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grade3ActionPerformed(evt);
            }
        });

        Grade4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grade4ActionPerformed(evt);
            }
        });

        Grade5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grade5ActionPerformed(evt);
            }
        });

        jButton1.setText("GRADE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("AVERAGE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(Sub5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(Sub4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(Sub2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(Sub1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(Sub3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Grade2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Grade1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Grade4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Grade3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Grade5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(totAvg1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)))))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Grade3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Grade4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Grade5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Grade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Grade2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Sub1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Sub2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Sub3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Sub4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Sub5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totAvg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Sub1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sub1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sub1ActionPerformed

    private void Sub2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sub2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sub2ActionPerformed

    private void Sub3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sub3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sub3ActionPerformed

    private void Sub4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sub4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sub4ActionPerformed

    private void Sub5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sub5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sub5ActionPerformed

    private void Grade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grade1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Grade1ActionPerformed

    private void Grade2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grade2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Grade2ActionPerformed

    private void Grade3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grade3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Grade3ActionPerformed

    private void Grade4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grade4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Grade4ActionPerformed

    private void Grade5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grade5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Grade5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int Subj1 = Integer.parseInt(Sub1.getText());        
        int Subj2 = Integer.parseInt(Sub2.getText());   
        int Subj3 = Integer.parseInt(Sub3.getText());
        int Subj4 = Integer.parseInt(Sub4.getText());
        int Subj5 = Integer.parseInt(Sub5.getText());
        
        
        if (Subj1 >= 90 && Subj1 <= 100) {       
            Grade1.setText("A");   
        } else if (Subj1 >= 80 && Subj1 <= 89) {
            Grade1.setText("B");
        } else if (Subj1 >= 70 && Subj1 <= 79) {
            Grade1.setText("C");
        } else if (Subj1 >= 60 && Subj1 <= 69) {
            Grade1.setText("D");
        } else if (Subj1 >= 50 && Subj1 <= 59) {
            Grade1.setText("D-");
        } else if (Subj1 >= 0 && Subj1 <= 49) {
            Grade1.setText("F");  
        } 
        
        
        if (Subj2 >= 90 && Subj2 <= 100) {       
            Grade2.setText("A");   
        } else if (Subj2 >= 80 && Subj2 <= 89) {
            Grade2.setText("B");
        } else if (Subj2 >= 70 && Subj2 <= 79) {
            Grade2.setText("C");
        } else if (Subj2 >= 60 && Subj2 <= 69) {
            Grade2.setText("D");
        } else if (Subj2 >= 50 && Subj2 <= 59) {
            Grade2.setText("D-");
        } else if (Subj2 >= 0 && Subj2 <= 49) {
            Grade2.setText("F");  
        } 
        
        
        if (Subj3 >= 90 && Subj3 <= 100) {       
            Grade3.setText("A");   
        } else if (Subj3 >= 80 && Subj3 <= 89) {
            Grade3.setText("B");
        } else if (Subj3 >= 70 && Subj3 <= 79) {
            Grade3.setText("C");
        } else if (Subj3 >= 60 && Subj3 <= 69) {
            Grade3.setText("D");
        } else if (Subj3 >= 50 && Subj3 <= 59) {
            Grade3.setText("D-");
        } else if (Subj3 >= 0 && Subj3 <= 49) {
            Grade3.setText("F");  
        }    
        
        
        if (Subj4 >= 90 && Subj4 <= 100) {       
            Grade4.setText("A");   
        } else if (Subj4 >= 80 && Subj4 <= 89) {
            Grade4.setText("B");
        } else if (Subj4 >= 70 && Subj4 <= 79) {
            Grade4.setText("C");
        } else if (Subj4 >= 60 && Subj4 <= 69) {
            Grade4.setText("D");
        } else if (Subj4 >= 50 && Subj4 <= 59) {
            Grade4.setText("D-");
        } else if (Subj4 >= 0 && Subj4 <= 49) {
            Grade4.setText("F");  
        }    
        
        if (Subj5 >= 90 && Subj5 <= 100) {       
            Grade5.setText("A");   
        } else if (Subj5 >= 80 && Subj5 <= 89) {
            Grade5.setText("B");
        } else if (Subj5 >= 70 && Subj5 <= 79) {
            Grade5.setText("C");
        } else if (Subj5 >= 60 && Subj5 <= 69) {
            Grade5.setText("D");
        } else if (Subj5 >= 50 && Subj5 <= 59) {
            Grade5.setText("D-");
        } else if (Subj5 >= 0 && Subj5 <= 49) {
            Grade5.setText("F");  
        }    

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        float Avg1 = Integer.parseInt(Sub1.getText());        
        float Avg2 = Integer.parseInt(Sub2.getText());   
        float Avg3 = Integer.parseInt(Sub3.getText());
        float Avg4 = Integer.parseInt(Sub4.getText());
        float Avg5 = Integer.parseInt(Sub5.getText());
        
        double totAvg = (Avg1 + Avg2 + Avg3 + Avg4 + Avg5)/5;
        
         totAvg1.setText(totAvg+"");

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GradeCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GradeCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GradeCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GradeCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GradeCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Grade1;
    private javax.swing.JTextField Grade2;
    private javax.swing.JTextField Grade3;
    private javax.swing.JTextField Grade4;
    private javax.swing.JTextField Grade5;
    private javax.swing.JTextField Sub1;
    private javax.swing.JTextField Sub2;
    private javax.swing.JTextField Sub3;
    private javax.swing.JTextField Sub4;
    private javax.swing.JTextField Sub5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField totAvg1;
    // End of variables declaration//GEN-END:variables
}
